<div class="match-group">
    <?php /* Using hidden input below to set default as ALL
    echo $this->formSelect((new \Laminas\Form\Element\Select($namePrefix . '[match]'))->setValueOptions([
        'all' => $this->translate('Match ALL of the following:'),
        'any' => $this->translate('Match ANY of the following:'),
    ])->setValue(!empty($data) ? $data['match'] : '')); */ ?>
    <input type="hidden" name="filters[match]" value="all" />
    <?php if (!$mainGroup): ?>
        <button type="button" class="o-icon-delete search-delete-filter"></button>
    <?php endif; ?>

    <div class="match-group-items">
        <?php if (!empty($data['queries'])): ?>
            <?php foreach($data['queries'] as $i => $query): ?>
                <div class="match-group-item">
                    <?php if (isset($query['match'])): ?>
                        <?php echo $this->partial('search/form/standard-match-group', [
                            'availableFieldsOptions' => $availableFieldsOptions,
                            'availableOperatorsOptions' => $availableOperatorsOptions,
                            'data' => $query,
                            'namePrefix' => $namePrefix . "[queries][$i]",
                            'mainGroup' => false,
                        ]); ?>
                    <?php else: ?>
                        <?php echo $this->partial('search/form/standard-match-group-filter', [
                            'availableFieldsOptions' => $availableFieldsOptions,
                            'availableOperatorsOptions' => $availableOperatorsOptions,
                            'query' => $query,
                            'namePrefix' => $namePrefix . "[queries][$i]",
                        ]); ?>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="match-group-item">
                <?php echo $this->partial('search/form/standard-match-group-filter', [
                    'availableFieldsOptions' => $availableFieldsOptions,
                    'availableOperatorsOptions' => $availableOperatorsOptions,
                    'query' => [],
                    'namePrefix' => $namePrefix . '[queries][0]',
                ]); ?>
            </div>
            <div class="match-group-item">
                <?php echo $this->partial('search/form/standard-match-group-filter', [
                    'availableFieldsOptions' => $availableFieldsOptions,
                    'availableOperatorsOptions' => $availableOperatorsOptions,
                    'query' => [],
                    'namePrefix' => $namePrefix . '[queries][1]',
                ]); ?>
            </div>
        <?php endif; ?>

        <div class="match-group-add-filter">
            <a href="#" class="btn btn-secondary search-add-filter"><i class="fa-solid fa-plus"></i> <?php echo $this->translate('Add filter'); ?></a>
        </div>
    </div>
</div>
