<?php
    $fieldSelect = new \Laminas\Form\Element\Select($namePrefix . '[field]');
    $fieldSelect->setValueOptions($availableFieldsOptions);
    if (isset($query['field'])) {
        $fieldSelect->setValue($query['field']);
    }
    $fieldSelect->setAttribute('class', 'search-form-standard-filter-field');
    echo $this->formSelect($fieldSelect);
?>

<?php /* Using hidden input below for default value of 'match any'
    $operatorSelect = new \Laminas\Form\Element\Select($namePrefix . '[operator]');
    $operatorSelect->setValueOptions($availableOperatorsOptions);
    if (isset($query['operator'])) {
        $operatorSelect->setValue($query['operator']);
    }
    $operatorSelect->setAttribute('class', 'search-form-standard-filter-operator');
    echo $this->formSelect($operatorSelect); */
    $operatorSelect = new \Laminas\Form\Element\Hidden($namePrefix . '[operator]');
    $operatorSelect->setValue('contains_any_word');
    echo $this->formHidden($operatorSelect); 
?>

<?php
    $termText = new \Laminas\Form\Element\Text($namePrefix . '[term]');
    if (isset($query['term'])) {
        $termText->setValue($query['term']);
    }
    $termText->setAttribute('class', 'search-form-standard-filter-term');
    echo $this->formText($termText);
?>

<button type="button" class="o-icon-delete search-delete-filter"></button>
