<?php $items = $this->randomGdaoItems((int) $block->dataValue('count', 3)); ?>
<div class="col-4 mx-4">
    <h2>Random from the Archive</h2>
    <div class="item-showcase">
        <?php foreach ($items as $item): ?>
            <div class="item resource">
                <?php $media = $item->primaryMedia(); ?>
                <?php if ($media): ?>
                    <?php echo $item->linkRaw($this->thumbnail($media, 'square')); ?>
                <?php endif; ?>

                <h3><?php echo $item->link($item->displayTitle()); ?></h3>
            </div>
        <?php endforeach; ?>
    </div>
</div>
