<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var bool $commentThreaded
 *
 * Customized from the Comment module for UCSC. Changes the logic
 * to only print the comment wrapper and heading if comments
 * exist.
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$url = $plugins->get('url');
$setting = $plugins->get('setting');
$assetUrl = $plugins->get('assetUrl');
$partial = $plugins->get('partial');

$this->headLink()->appendStylesheet($assetUrl('css/comment.css', 'Comment'));
$this->headScript()->appendFile($assetUrl('js/comment.js', 'Comment'), 'text/javascript', ['defer' => 'defer']);

// Required to manage the base path.
$addUrl = $url('site/comment', ['action' => 'add'], true);
?>

<?php if (!empty($comments)): ?>
    <div id="comments" class="comments" data-comment-url="<?= $addUrl ?>">
        <?php if ($label = $setting('comment_comments_label')): ?>
            <h2><?= $translate($label) ?></h2>
        <?php endif; ?>

        <?php if ($setting('comment_threaded')): ?>
            <?= $partial('common/comments-thread', ['comments' => $comments, 'parent_id' => null]) ?>
        <?php else: ?>
            <?= $partial('common/comments-list', ['comments' => $comments]) ?>
        <?php endif; ?>
    </div>
<?php endif; ?>
