<?php
    $propertyValues = $propertyData['values'];
    if ($filterLocale) {
        $propertyValues = array_filter($propertyValues, $filterLocaleCallback);
    }
    if (!$propertyValues) {
        return;
    }
    $property = $propertyData['property'];
    $propertyLabel = $propertyData['alternate_label'] ?: $translate($property->label());
    if ('term' === $labelInfo) {
        $propertyTerm = $property->term();
    } elseif ('vocab' === $labelInfo) {
        $propertyTerm = $property->vocabulary()->label();
    } else {
        $propertyTerm = null;
    }
    $facetName = str_replace(':', '_', $term);
?>
    <div class="property">
        <dt>
        <?php echo $escape($propertyLabel); ?>
        <?php if ($propertyTerm !== null): ?>
        <span class="field-term">(<?php echo $escape($propertyTerm); ?>)</span>
        <?php endif; ?>
        </dt>
        <?php foreach ($propertyValues as $value): ?>
        <?php
        $valueType = $value->type();
        $valueLang = $value->lang();
        $valueAnnotation = $value->valueAnnotation();
        $class = ['value'];
        if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
            $class[] = 'resource';
            $class[] = $escape($value->valueResource()->resourceName());
        } elseif ('uri' == $valueType) {
            $class[] = 'uri';
        }
        ?>
        <dd class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($valueLang); ?>">
            <?php if ($showLocale && $valueLang): ?>
            <span class="language"><?php echo $valueLang; ?></span>
            <?php endif; ?>
            <?php
                $valuePrinted = $filterLocale ? $value->asHtml($lang) : $value->asHtml();
                $valueUrl = $this->GdaoSearchUrl(null, [$facetName => $value->value()]);
            ?>
            <?php if (in_array($facetName, $facetValues)) : ?>
                <a class="value-content" href="<?php echo $valueUrl; ?>"><?php echo $valuePrinted; ?></a>
            <?php else : ?>
                <span class="value-content"><?php echo $valuePrinted; ?></span>
            <?php endif; ?>
            <?php if(!$value->isPublic()): ?>
                <span class="o-icon-private" aria-role="tooltip" title="<?php echo $this->escapeHtml($translate('Private')); ?>" aria-label="<?php echo $this->escapeHtml($translate('Private')); ?>"></span>
            <?php endif; ?>
            <?php if ($valueAnnotation && $showValueAnnotations): ?>
                <a href="#" class="expand" aria-label="<?php echo $this->escapeHtml($translate('Expand')); ?>">
                    <span class="has-annotation o-icon-annotation" aria-role="tooltip" title="<?php echo $this->escapeHtml($translate('Has annotation')); ?>" aria-label="<?php echo $this->escapeHtml($translate('Has annotation')); ?>"></span>
                </a>
                <div class="collapsible annotation">
                    <?php echo $valueAnnotation->displayValues(); ?>
                </div>
            <?php endif; ?>
            <?php $this->trigger('view.show.value', ['value' => $value]); ?>
        </dd>
        <?php endforeach; ?>
    </div>