<?php
$translate = $this->plugin('translate');
$searchUrl = $this->escapeHtml($this->url('search-page-1', [], true));
?>

<form
    action="<?php echo $searchUrl; ?>"
    id="search-form" class="mb-0 input-group">
    <input type="text" name="filters[queries][0][term]" class="form-control" value=""
        placeholder="<?php echo $translate('Search'); ?>">
    <input type="hidden" name="filters[queries][0][field]" value="keyword" />
    <input type="hidden" name="filters[queries][0][operator]" value="contains_any_word" />
    <input type="hidden" name="filters[match]" value="all" />
    <button class="btn btn-primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
</form>
<div><a href="<?php echo $searchUrl; ?>">Advanced Search</a></div>
