<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();

function process_theme_values($values = "") {
    if ($values != "") {
        $values = explode("\n", $values);
        return array_map('trim', $values);
    }
    else {
        return array();
    }
}
?>

<?php $this->trigger('view.show.before'); ?>

<div class="container mb-5">
    <?php echo $this->pageTitle($item->displayTitle(null, ($filterLocale ? $lang : null)), 2); ?>

    <!-- <h3><?php echo $translate('Item'); ?></h3> -->

    <div class="row main">
        <div class="col col-9 main">
            <?php echo $this->resourcePageBlocks($item, 'main')->getBlocks(); ?>
        </div>

        <div class="col col-3 sidebar">
            <?php echo $this->resourcePageBlocks($item, 'sidebar')->getBlocks(); ?>
        </div>
    </div>

    <div class="row secondary">
        <div class="col col-12 text-center">
            <button class="btn btn-secondary" id="item-details-btn">Show Details</button>
        </div>
        <div class="col col-12 secondary" id="item-details">
            <?php echo $this->resourcePageBlocks($item, 'secondary')->getBlocks(); ?>
        </div>

        <?php $this->trigger('view.show.after'); ?>
    </div>
</div>

<script>
$(document).ready(function() {
    $('#item-details').hide();

    var more = false;
    $('#item-details-btn').click(function() {
        if(more) {
            $('#item-details').slideUp();
            $(this).html('Show Details');
        } else {
            $('#item-details').slideDown();
            $(this).html('Hide Details');
        }
        more = !more;
    });
});
</script>
