<?php 
// Customized for GDAO.
// We use this block on exhibit pages, but it tries to link the item back to the 
// resource within the exhibit site. We hardcode the link back to the item show page
// in the main gdao site.
?>
<div class="row item-showcase">
  <?php foreach ($attachments as $attachment): ?>
    <div class="col-4">
      <div class="mb-3">
        <?php
        $item = $attachment->item();
        if ($item):
          if ($heading = $block->dataValue('heading')) {
            echo "<h3>" . $heading . "</h3>";
          } ?>

          <!-- Card image -->
          <div class="text-center bg-light">
            <?php
            $media = $attachment->media() ?: $item->primaryMedia();
            if ($media):
                echo '<a href="/items/show/' . $item->value('gdao:classicID') . '">';
                echo $this->thumbnail($media, $this->thumbnailType);
                echo '</a>';
            endif;
            $showTitleOption = $this->showTitleOption;
            if ($showTitleOption == 'item_title') {
              echo '<h5 class="card-text">' . $item->link($item->displayTitle()) . '</h5>';
            }
            elseif ($showTitleOption == 'file_name') {
              echo '<p class="card-text">' . $media->displayTitle() . '</p>';
            } ?>
          </div>
          <div class="card-body">
            <?php
            if ($caption = $attachment->caption()) {
              echo '<div class="caption">' . $caption . '</div>';
            } ?>
          </div>
        </div>

      <?php endif; ?>
    </div>
  <?php endforeach; ?>
</div>
