<?php
/*
 * Copyright BibLibre, 2016
 * Copyright University of California, Santa Cruz, 2023
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php $escape = $this->plugin('escapeHtml'); ?>

<<?php echo $tag; ?> class="<?php echo $resource->resourceName(); ?> resource">
    <?php if (method_exists($resource, 'primaryMedia') && $primaryMedia = $resource->primaryMedia()): ?>
        <a href="<?php echo $resource->url() ?>"><img
            src="<?php echo $escape($primaryMedia->thumbnailUrl('square')); ?>"
            title="<?php echo $escape($primaryMedia->displayTitle()); ?>"
            alt="<?php echo $escape($primaryMedia->mediaType()); ?> thumbnail"
        /></a>
    <?php endif; ?>
    <div class="metadata-set">
        <h4><?php echo $resource->link($resource->displayTitle()); ?>
            <span class="item-type">(<?php echo $resource->displayResourceTemplateLabel(); ?>)</span>
        </h4>

        <?php $searchUrl = $this->url('search-page-1',[], ['query' => ['q' => '']]); ?>

        <?php if ($creator = $resource->value('dcterms:creator')): ?>
            <?php $creatorUrl = $searchUrl . "&limit[creator][0]=" . $creator->value(); ?>
            <div class="metadata">
                <span class="label">Creator:</span>
                <span class="value"><a href="<?php echo $creatorUrl  ?>"><?php echo $creator ?></a></span>
            </div>
        <?php endif; ?>

        <?php if ($relatedShow = $resource->value('dcterms:coverage')): ?>
            <?php $relatedUrl = $searchUrl . "&limit[coverage][0]=" . $relatedShow->value(); ?>
            <div class="metadata">
                <span class="label">Related Show:</span>
                <span class="value"><a href="<?php echo $relatedUrl  ?>"><?php echo $relatedShow ?></a></span>
            </div>
        <?php endif; ?>
    </div>

</<?php echo $tag ?>>
