<?php
/*
 * Copyright BibLibre, 2016
 * Copyright University of California, Santa Cruz, 2023
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

    $escape = $this->plugin('escapeHtml');
    $images = array(
        'Sound' => 'itemtype-sound.png',
        'Video' => 'itemtype-video.png',
        'Story' => 'itemtype-oralhistory.png',
        'Article' => 'itemtype-article.png',
        'Website' => 'itemtype-website.png',
    );
    $title = $resource->displayTitle();
    $type = $resource->displayResourceTemplateLabel();
    $values = $resource->values();
?>

<<?php echo $tag; ?> class="<?php echo $resource->resourceName(); ?> resource">
    <div class="resource-thumbnail">
        <a href="<?php echo $resource->url() ?>">
        <?php if (method_exists($resource, 'primaryMedia') && $primaryMedia = $resource->primaryMedia()): ?>
            <img
                src="<?php echo $escape($primaryMedia->thumbnailUrl('square')); ?>"
                title="<?php echo $escape($primaryMedia->displayTitle()); ?>"
                alt="<?php echo $escape($primaryMedia->mediaType()); ?> thumbnail"
            />
        <?php elseif (array_key_exists($type, $images)) : ?>
            <?php if (($resource->value('gdao:accessRestricted') != "true") || $this->GdaoIsAuthorized()) : ?>
                <?php $image = "themes/gdao-s-theme/asset/img/icon/" . $images[$type]; ?>
                <img src="<?php echo $image; ?>" alt="<?php echo $title; ?>" title="<?php echo $title; ?>" />
            <?php else : ?>
                <img src="/themes/gdao-s-theme/asset/img/content-not-available.png" alt="Image not available due to copyright restrictions" title="<?php echo $title; ?>" />
            <?php endif; ?>
        <?php elseif ($resource->value('dcterms:source') == "Internet Archive") : ?>
            <img src="/themes/gdao-s-theme/asset/img/ia-logo-sm.png" alt="<?php echo $title; ?> thumbnail" title="<?php echo $title; ?>" />
        <?php else : ?>
            <img src="/themes/gdao-s-theme/asset/img/logo-gdao-gray.png" alt="<?php echo $title; ?> thumbnail" title="<?php echo $title; ?>" />
        <?php endif; ?>
        </a>
    </div>
    <div class="metadata-set">
        <h4><?php echo $resource->link($resource->displayTitle()); ?>
            <?php if (!in_array($type, ['Backstage Pass', 'Album Cover', 'Laminate'])) : ?>
                <span class="item-type">(<?php echo $resource->displayResourceTemplateLabel(); ?>)</span>
            <?php endif; ?>
        </h4>

        <?php if (isset($values['dcterms:creator'])) : ?>
            <div class="metadata">
                <?php
                $creators = $values['dcterms:creator']['values'];
                $label = count($creators) > 1 ? 'Creators:' : 'Creator:';
                ?>
                <span class="label"><?php echo $label; ?></span>
                <?php foreach ($creators as $value) : ?>
                    <?php $url = $this->GdaoSearchUrl(null, ['dcterms_creator' => $value->value()]); ?>
                    <span class="value"><a href="<?php echo $url  ?>"><?php echo $value->value() ?></a></span>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php if (isset($values['dcterms:coverage'])) : ?>
            <div class="metadata">
                <?php
                $shows = $values['dcterms:coverage']['values'];
                $label = count($shows) > 1 ? 'Related Shows:' : 'Related Show:';
                ?>
                <span class="label"><?php echo $label; ?></span>
                <?php foreach ($shows as $value) : ?>
                    <?php $url = $this->GdaoSearchUrl(null, ['dcterms_coverage' => $value->value()]); ?>
                    <span class="value"><a href="<?php echo $url  ?>"><?php echo $value->value() ?></a></span>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
    </div>

</<?php echo $tag ?>>
